namespace: monitoring

resources:
  - ../../base

helmGlobals:
  chartHome: ../../base

helmCharts:
  - name: victoria-metrics-agent
    releaseName: victoria-metrics-agent
    namespace: monitoring
    valuesFile: ha-values.yaml

