namespace: monitoring

resources:
  - ../../base

helmGlobals:
  chartHome: ../../base

helmCharts:
  - name: victoria-logs-cluster
    releaseName: victoria-logs
    namespace: monitoring
    valuesFile: ha-values.yaml
