remoteWrite:
  - url: http://victoria-metrics-victoria-metrics-cluster-vminsert.monitoring.svc.cluster.local:8480/insert/0/prometheus


resources: {}

config:
  global:
    scrape_interval: 20s
  scrape_configs:
    - job_name: 'node-exporter'
      kubernetes_sd_configs:
        - role: endpoints
          namespaces:
            names: ['monitoring']
      relabel_configs:
        - source_labels: [__meta_kubernetes_service_label_app_kubernetes_io_name]
          regex: prometheus-node-exporter
          action: keep
        - source_labels: [__meta_kubernetes_endpoints_node_name]
          target_label: node
