fileConfigs:
  02_outputs.conf: |-
    <match kubernetes.**>
      @type copy
      # 1つ目の送り先: Loki
      <store>
        @type loki
        url "http://loki-write.logging.svc.cluster.local:3100"
        <buffer>
          @type file
          path /var/log/fluentd-loki.buffer
        </buffer>
      </store>
      # 2つ目の送り先: VictoriaLogs
      <store>
        @type http
        endpoint "http://vlogs.logging.svc.cluster.local:9428/insert/jsonline?_stream_fields=container_name,namespace"
        <format>
          @type json
        </format>
        <buffer>
          @type file
          path /var/log/fluentd-vlogs.buffer
        </buffer>
      </store>
    </match>
