namespace: monitoring

resources:
  - ../../base

helmGlobals:
  chartHome: ../../base

helmCharts:
  - name: victoria-metrics-cluster
    releaseName: victoria-metrics
    namespace: monitoring
    valuesFile: ha-values.yaml
