resources:
  - github.com/VictoriaMetrics/operator/config/base-with-webhook?ref=v0.66.0

patchesStrategicMerge:
  - vm-operator-deploy-patch.yaml

namespace: monitoring

images:
- name: manager
  newName: victoriametrics/operator
  newTag: v0.66.0
